language: python
python:
  - "2.7"
before_install:
  - ./install_mongo.sh
install: pip install -r requirements.txt
before_script:
  - "flake8 tavi"
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
script:  python setup.py nosetests
env:
  - "PYMONGO_VERSION='== 2.4.1' MONGO_VERSION=2.6.12"
  - "PYMONGO_VERSION='>= 2.8.0, < 3.0.0' MONGO_VERSION=2.6.12"
  - "PYMONGO_VERSION='>= 2.8.0, < 3.0.0' MONGO_VERSION=3.0.11"
  - "PYMONGO_VERSION='>= 3.2.0, < 4.0.0' MONGO_VERSION=2.6.12"
  - "PYMONGO_VERSION='>= 3.2.0, < 4.0.0' MONGO_VERSION=3.0.11"
  - "PYMONGO_VERSION='>= 3.2.0, < 4.0.0' MONGO_VERSION=3.2.6"
sudo: required
